name: vaccitaly
description: Dati vaccini Italia.

publish_to: 'none'

version: 0.3.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  url_launcher: ^5.7.10
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons.png"

flutter:
  uses-material-design: true
